services:
  cs2:
    image: joedwards32/cs2 # https://github.com/joedwards32/CS2
    container_name: cs2
    hostname: cs2
    restart: unless-stopped

    environment:
      SRCDS_TOKEN: $SRCDS_TOKEN
      CS2_SERVERNAME: $CS2_SERVERNAME
      CS2_CHEATS: $CS2_CHEATS
      CS2_SERVER_HIBERNATE: $CS2_SERVER_HIBERNATE
      STEAMAPPVALIDATE: $STEAMAPPVALIDATE
      CS2_MAXPLAYERS: $CS2_MAXPLAYERS
      CS2_IP: $CS2_IP
      CS2_PORT: $CS2_PORT
      CS2_LAN: $CS2_LAN
      CS2_RCONPW: $CS2_RCONPW
      CS2_PW: $CS2_PW
      CS2_GAMEALIAS: $CS2_GAMEALIAS
      CS2_MAPGROUP: $CS2_MAPGROUP
      CS2_STARTMAP: $CS2_STARTMAP
      CS2_BOT_DIFFICULTY: $CS2_BOT_DIFFICULTY
      CS2_BOT_QUOTA: $CS2_BOT_QUOTA
      CS2_BOT_QUOTA_MODE: $CS2_BOT_QUOTA_MODE
      TV_AUTORECORD: $TV_AUTORECORD
      TV_ENABLE: $TV_ENABLE
      TV_PORT: $TV_PORT
      TV_PW: $TV_PW
      TV_RELAY_PW: $TV_RELAY_PW
      TV_MAXRATE: $TV_MAXRATE
      TV_DELAY: $TV_DELAY
      CS2_LOG: $CS2_LOG
      CS2_LOG_MONEY: $CS2_LOG_MONEY
      CS2_LOG_DETAIL: $CS2_LOG_DETAIL
      CS2_LOG_ITEMS: $CS2_LOG_ITEMS
      CS2_HOST_WORKSHOP_MAP: $CS2_HOST_WORKSHOP_MAP
      CS2_HOST_WORKSHOP_COLLECTION: $CS2_HOST_WORKSHOP_COLLECTION
      DEBUG: $DEBUG

    volumes:
      - ./data:/home/steam/cs2-dedicated/ # Persistent data volume mount point inside container

    ports:
      - "$CS2_PORT:27015/tcp" # TCP
      - "$CS2_PORT:27015/udp" # UDP
      - "27020:27020/udp" # UDP

    stdin_open: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated
    tty: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated

    networks:
      - cs2

networks:
  cs2:
    driver: bridge
