services:
  cs2:

    # https://github.com/joedwards32/CS2
    image: joedwards32/cs2

    container_name: cs2

    environment:
      # Server configuration
      SRCDS_TOKEN: $GAME_SERVER_TOKEN # Game Server Token from https://steamcommunity.com/dev/managegameservers
      CS2_SERVERNAME: "Santhor's server" # (Set the visible name for your private server)

      CS2_CHEATS: 1 # (0 - disable cheats, 1 - enable cheats)
      CS2_SERVER_HIBERNATE: 0 # (Put server in a low CPU state when there are no players. 0 - hibernation disabled, 1 - hibernation enabled)
      STEAMAPPVALIDATE: 1 # (0=skip validation, 1=validate game files)

      CS2_MAXPLAYERS: 12 # (Max players)

      CS2_IP=: ""
      CS2_PORT: $CS2_PORT # (CS2 server listen port tcp_udp)
      CS2_LAN: 1 # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      CS2_RCONPW: "@Pass123" # (RCON password)
      CS2_PW: "@Pass123" # (CS2 server password)

      # Game modes
      CS2_GAMEALIAS: "casual" # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_MAPGROUP: "mg_active" # (Map pool)
      CS2_STARTMAP: "de_mirage" # (Start map)

      # Bots
      CS2_BOT_DIFFICULTY: 0 # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      CS2_BOT_QUOTA: 0 # (Number of bots)
      CS2_BOT_QUOTA_MODE: "" # (fill, competitive)

      # TV
      TV_AUTORECORD: 0 # Automatically records all games as CSTV demos: 0=off, 1=on.
      TV_ENABLE: 0 # Activates CSTV on server: 0=off, 1=on.
      TV_PORT: 27020 # Host SourceTV port
      TV_PW: "@Pass123" # CSTV password for clients
      TV_RELAY_PW: "@Pass123" # CSTV password for relay proxies
      TV_MAXRATE: 0 # World snapshots to broadcast per second. Affects camera tickrate.
      TV_DELAY: 0 # CSTV broadcast delay in seconds

      # Logs
      CS2_LOG: "on" # 'on'/'off'
      CS2_LOG_MONEY: 0 # Turns money logging on/off: (0=off, 1=on)
      CS2_LOG_DETAIL: 0 # Combat damage logging: (0=disabled, 1=enemy, 2=friendly, 3=all)
      CS2_LOG_ITEMS: 0 # Turns item logging on/off: (0=off, 1=on)

      # Steam Workshop
      CS2_HOST_WORKSHOP_MAP: "" #(Steam Workshop Map ID to load on server start)   
      CS2_HOST_WORKSHOP_COLLECTION: "" # (Steam Workshop Collection ID to download)

    volumes:
      - ./data:/home/steam/cs2-dedicated/ # Persistent data volume mount point inside container

    ports:
      - "$CS2_PORT:27015/tcp" # TCP
      - "$CS2_PORT:27015/udp" # UDP
      - "27020:27020/udp" # UDP

    stdin_open: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated
    tty: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated

    networks:
      - cs2

networks:
  cs2:
    driver: bridge
